[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
paste = "1"
lazy_static = "1.0.11"
seq-macro = "0.3"
pathfinding = "4.0"
clap = { version = "4.0", features = ["derive"] }
